name: Update AKS Operator in rancher/charts
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Branch to use for GitHub action workflow"
        required: true
        default: "release-v2.7"
      charts_ref:
        description: "Submit PR against the following rancher/charts branch (e.g. dev-v2.7)"
        required: true
        default: "dev-v2.7"
      prev_aks_operator:
        description: "Previous AKS operator version (e.g. 1.2.0-rc.1)"
        required: true
        default: ""
      new_aks_operator:
        description: "New AKS operator version"
        required: true
        default: ""
      prev_chart:
        description: "Previous Rancher Chart version (e.g. 101.1.0)"
        required: true
        default: ""
      new_chart:
        description: "New Rancher Chart version"
        required: true
        default: ""
      should_replace:
        description: "Should the old AKS operator version be replaced/removed? (e.g. true in case of release candidate bumps)"
        required: true
        default: "true"

jobs:
  create-rancher-charts-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{github.event.inputs.ref}}
          path: aks-operator
          persist-credentials: false
      - name: Checkout rancher/charts
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: rancher/charts
          ref: ${{github.event.inputs.charts_ref}}
          path: charts
          persist-credentials: false
      - name: Run release script # release script is responsible for git add/commit
        run: ./aks-operator/.github/scripts/update-rancher-charts.sh ${{github.event.inputs.prev_aks_operator}} ${{github.event.inputs.new_aks_operator}} ${{github.event.inputs.prev_chart}}  ${{github.event.inputs.new_chart}}  ${{github.event.inputs.should_replace}}
      - name: Set timestamp
        run: echo "TIMESTAMP=$(date +'%s')" >> "$GITHUB_ENV"
      - name: Push changes
        env:
          USERNAME: highlander-ci-bot
          TOKEN: ${{ secrets.CI_BOT_TOKEN }}
        run: |
          git remote add bot-fork https://${USERNAME}:${TOKEN}@github.com/highlander-ci-bot/charts.git
          git push bot-fork HEAD:${{github.event.inputs.new_aks_operator}}-${{env.TIMESTAMP}}
      - name: Create PR
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          github-token: ${{ secrets.CI_BOT_TOKEN }}
          script: |
            github.pulls.create({
              owner: 'rancher',
              repo: 'charts',
              head: 'highlander-ci-bot:${{github.event.inputs.new_aks_operator}}-${{env.TIMESTAMP}}',
              base: ${{github.event.inputs.charts_ref}},
              title: 'Update AKS operator to v${{github.event.inputs.new_aks_operator}}',
              body: 'Update AKS operator to v${{github.event.inputs.new_aks_operator}}\n\nChangelog: https://github.com/rancher/aks-operator/releases/tag/v${{github.event.inputs.new_aks_operator}}\n\ncc @rancher/highlander'
            })

